### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bernaferrari** [bridgedxyz/plugins#5]
Hey, author of [Figma to Code](https://github.com/bernaferrari/FigmaToCode) here. Congrats on your project! Looks really amazing. Only two things:

1. You mention that my project has MIT license. I'm not sure where you saw MIT, but the license in my project is GPL-3.0 (which means, do whatever you want as long as you publish your modifications, which you kind of already voluntarily did :P).

2. I'm happy to merge-back any changes that you've made or any suggestions that you have back into Figma to Code (like the formatted code) unless they are too complicated. I haven't taken a look into what your modifications were, but if you could brief me, I would be happy.

**Comment by softmarshmallow** [comment]
@bernaferrari I am very sorry. my mistake. I will remove all your codes, re-write from scratch. since this repository is linked with others, i'de like to make rm commit for the file, and re-start. 

If you say that is fine, I'll do that.
If you say no, I'll remove this repository and create new one from code of my own.

the plugin will have other capabilities and directions, so i'm not thinking of merging it to yours.

Have a good day!

**Comment by bernaferrari** [comment]
Technically GPL doesn't prevent you from linking other things, it just says that you should make open any modifications to the original. Apple uses bash, but macOS is not open source, they just publish the source of their modified bash. So, it doesn't matter what you use together, as long as the module/plugin that modified my code is open, which seems like so.
And technically, even if you remove my code, then writes a similar implementation, that is dirty because mine influenced you. 😜

I made it GLPv3 to avoid giving unfair advantage to other products/companies. 
But I would say, sure, feel free to keep using it. You are already developing in the open, so that's not an issue.

**Comment by softmarshmallow** [comment]
Sure, thanks for the reply. I will understand the miss notice of the license was my mistake, I will update the docs, and ASAP re write all the codes (I just prefer this). And you have no problem with this since the code is open. (and kept this way).

There was no intend to violate the license, it was my big mistake, I will email you personally when all the origin code is removed and refreshed. so you can feel free about it.

My apologies again. Thanks.

**Comment by bernaferrari** [comment]
No problem.. Don't worry. I've also had some GPLv3 issues in the past 😜. I only made it this way in this project to avoid unfair competition, but you don't have to worry.. And, if you so wish, feel free to keep it that way. It is only a minor detail. Thanks anyway!
